spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8081